"""Build and persist a FAISS index plus its source-text metadata."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

import faiss
import numpy as np

from .chunking import Chunk


INDEX_FILE = "vectors.faiss"
METADATA_FILE = "metadata.json"
SCHEMA_VERSION = 1


@dataclass
class PreparedIndex:
    index: faiss.Index
    chunks: list[Chunk]
    document_id: str
    source_filename: str
    source_sha256: str
    embedding_model: str
    chunk_size: int
    overlap: int


@dataclass(frozen=True)
class SearchResult:
    rank: int
    score: float
    chunk: Chunk


def build_index(
    chunks: list[Chunk],
    vectors: np.ndarray,
    *,
    source_filename: str,
    source_sha256: str,
    embedding_model: str,
    chunk_size: int,
    overlap: int,
) -> PreparedIndex:
    """Store unit-length vectors in an exact inner-product FAISS index."""
    if not chunks:
        raise ValueError("Cannot build an index without chunks")
    if len({chunk.document_id for chunk in chunks}) != 1:
        raise ValueError("Each index must contain chunks from one document")
    if [chunk.chunk_id for chunk in chunks] != list(range(len(chunks))):
        raise ValueError("Chunk IDs must be consecutive, starting at zero")

    matrix = np.asarray(vectors, dtype=np.float32)
    if matrix.ndim != 2 or matrix.shape[0] != len(chunks) or matrix.shape[1] == 0:
        raise ValueError("Vector shape must be (number_of_chunks, dimension)")
    if not np.isfinite(matrix).all():
        raise ValueError("Vectors must contain only finite numbers")
    lengths = np.linalg.norm(matrix, axis=1)
    if np.any(lengths == 0):
        raise ValueError("Zero-length vectors cannot be normalized")
    normalized = np.ascontiguousarray(matrix / lengths[:, None], dtype=np.float32)

    index = faiss.IndexFlatIP(normalized.shape[1])
    index.add(normalized)
    return PreparedIndex(
        index=index,
        chunks=chunks,
        document_id=chunks[0].document_id,
        source_filename=source_filename,
        source_sha256=source_sha256,
        embedding_model=embedding_model,
        chunk_size=chunk_size,
        overlap=overlap,
    )


def save_index(prepared: PreparedIndex, directory: str | Path) -> None:
    path = Path(directory)
    path.mkdir(parents=True, exist_ok=True)
    faiss.write_index(prepared.index, str(path / INDEX_FILE))
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "document_id": prepared.document_id,
        "source_filename": prepared.source_filename,
        "source_sha256": prepared.source_sha256,
        "embedding_model": prepared.embedding_model,
        "chunk_size": prepared.chunk_size,
        "overlap": prepared.overlap,
        "vector_count": prepared.index.ntotal,
        "dimension": prepared.index.d,
        "chunks": [asdict(chunk) for chunk in prepared.chunks],
    }
    (path / METADATA_FILE).write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def load_index(directory: str | Path) -> PreparedIndex:
    """Load an index generated by this application from trusted local files."""
    path = Path(directory)
    metadata = json.loads((path / METADATA_FILE).read_text(encoding="utf-8"))
    if metadata.get("schema_version") != SCHEMA_VERSION:
        raise ValueError("Unsupported index metadata version")
    index = faiss.read_index(str(path / INDEX_FILE))
    chunks = [Chunk(**item) for item in metadata["chunks"]]
    if index.ntotal != metadata["vector_count"] or index.ntotal != len(chunks):
        raise ValueError("FAISS vectors and chunk metadata have different counts")
    if index.d != metadata["dimension"]:
        raise ValueError("FAISS dimension and metadata disagree")
    if any(chunk.document_id != metadata["document_id"] for chunk in chunks):
        raise ValueError("Chunk document IDs do not match the index")
    return PreparedIndex(
        index=index,
        chunks=chunks,
        document_id=metadata["document_id"],
        source_filename=metadata["source_filename"],
        source_sha256=metadata["source_sha256"],
        embedding_model=metadata["embedding_model"],
        chunk_size=metadata["chunk_size"],
        overlap=metadata["overlap"],
    )


def search_index(
    prepared: PreparedIndex, query_vector: np.ndarray, *, top_k: int = 4
) -> list[SearchResult]:
    """Return the chunks whose vectors have the highest cosine similarity."""
    if top_k <= 0:
        raise ValueError("top_k must be positive")

    query = np.asarray(query_vector, dtype=np.float32)
    if query.ndim == 1:
        query = query.reshape(1, -1)
    if query.ndim != 2 or query.shape != (1, prepared.index.d):
        raise ValueError(
            f"Query vector must have shape (1, {prepared.index.d}), got {query.shape}"
        )
    if not np.isfinite(query).all():
        raise ValueError("Query vector must contain only finite numbers")

    length = np.linalg.norm(query, axis=1, keepdims=True)
    if length.item() == 0:
        raise ValueError("Query vector must not have zero length")
    query = np.ascontiguousarray(query / length, dtype=np.float32)

    count = min(top_k, prepared.index.ntotal)
    scores, vector_ids = prepared.index.search(query, count)
    return [
        SearchResult(
            rank=rank,
            score=float(score),
            chunk=prepared.chunks[int(vector_id)],
        )
        for rank, (score, vector_id) in enumerate(
            zip(scores[0], vector_ids[0], strict=True), start=1
        )
    ]
